### PR TITLE
Fix #240 Add ZK lib dir to Accumulo class path

### LINKED ISSUE #240: Uno no longer works with Accumulo 2.0.0
After the changes in #239 Uno no longer works with Accumulo 2.0.0 out of the box.  It does work with Accumulo 2.1.0-SNAPSHOT, maybe because that has apache/accumulo#1530.   When I revert #239 locally, Uno works with Accumulo 2.0.0.

Seeing the following error in `logs/setup/accumulo.out`

```
[ERROR] Error occurred at /home/ubuntu/git-local/fluo-uno/bin/impl/run/accumulo.sh:32 command: "$ACCUMULO_HOME"/bin/accumulo init --clear-instance-name --instance-name "$ACCUMULO_INSTANCE" --password "$ACCUMULO_PASSWORD"
```

Seeing the following error in `logs/setup/accumulo.err`.

```
2020-03-17 11:17:09,614 [start.Main] ERROR: Uncaught exception
java.util.ServiceConfigurationError: org.apache.accumulo.start.spi.KeywordExecutable: org.apache.accumulo.server.init.Initialize Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:672)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at org.apache.accumulo.start.Main.checkDuplicates(Main.java:243)
	at org.apache.accumulo.start.Main.getExecutables(Main.java:234)
	at org.apache.accumulo.start.Main.main(Main.java:88)
Caused by: java.lang.NoClassDefFoundError: org/apache/zookeeper/KeeperException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.KeeperException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 more

```

### PR DESCRIPTION
**Pull request by ctubbsii**
Add ZooKeeper 3.5.7's lib directory to Accumulo 2.0.0's class path in
conf/accumulo-env.sh

### CODE REVIEW

File: bin/impl/install/accumulo.sh [hunk 1]
```diff
@@ -59,6 +59,9 @@ else
   $SED "s#instance[.]zookeepers=localhost:2181#instance.zookeepers=$UNO_HOST:2181#" "$conf"/accumulo-client.properties
   $SED "s#auth[.]principal=#auth.principal=$ACCUMULO_USER#" "$conf"/accumulo-client.properties
   $SED "s#auth[.]token=#auth.token=$ACCUMULO_PASSWORD#" "$conf"/accumulo-client.properties
+  if [[ $ACCUMULO_VERSION =~ ^2\.0\.0.*$ ]]; then
```
Comment (keith-turner) [inline bin/impl/install/accumulo.sh]: I wonder it 1.9 and 1.10 work.

Comment (ctubbsii) [reply bin/impl/install/accumulo.sh]: Probably... but I have not tested. It's probably best that, if you want to run Uno with one of those versions of Accumulo, you do so by changing the ZooKeeper version as well, to the version that Accumulo has been tested with (3.4.14 is probably best).
